/**
 * Pool candidats mock pour l'aperçu UI du rapport pré-séance.
 * Remplacé par fetch banque réel (usePreSessionSelectionReport) en phase 2.
 */
import type { PreSessionCandidate } from "@/lib/pre-session-selection";

export const MOCK_PRE_SESSION_CANDIDATES: PreSessionCandidate[] = [
  {
    id: "mock-va-1",
    titre: "Compréhension — annonce logement",
    consigne: "Lisez le texte et répondez.",
    competence: "CE",
    niveau_vise: "A1",
    format: "qcm",
    contenu: { items: [{ question: "Q?", bonne_reponse: "a" }] },
    validation_status: "validated_auto",
    validation_issues: [],
    search_score: 92,
    fresh: true,
  },
  {
    id: "mock-va-2",
    titre: "Compréhension — horaires bus",
    consigne: "Lisez le texte et répondez.",
    competence: "CE",
    niveau_vise: "A1",
    format: "qcm",
    contenu: { items: [{ question: "Q?", bonne_reponse: "a" }] },
    validation_status: "validated_auto",
    validation_issues: [],
    search_score: 88,
    fresh: true,
  },
  {
    id: "mock-va-3",
    titre: "Compréhension — menu restaurant",
    consigne: "Lisez le texte et répondez.",
    competence: "CE",
    niveau_vise: "A1",
    format: "qcm",
    contenu: { items: [{ question: "Q?", bonne_reponse: "a" }] },
    validation_status: "validated_auto",
    validation_issues: [],
    search_score: 85,
    fresh: true,
  },
  {
    id: "mock-va-4",
    titre: "Compréhension — email collègue",
    consigne: "Lisez le texte et répondez.",
    competence: "CE",
    niveau_vise: "A1",
    format: "qcm",
    contenu: { items: [{ question: "Q?", bonne_reponse: "a" }] },
    validation_status: "validated_auto",
    validation_issues: [],
    search_score: 82,
    fresh: true,
  },
  {
    id: "mock-va-5",
    titre: "Compréhension — affiche événement",
    consigne: "Lisez le texte et répondez.",
    competence: "CE",
    niveau_vise: "A1",
    format: "qcm",
    contenu: { items: [{ question: "Q?", bonne_reponse: "a" }] },
    validation_status: "validated_auto",
    validation_issues: [],
    search_score: 80,
    fresh: true,
  },
  {
    id: "mock-va-6",
    titre: "Compréhension — consignes sécurité",
    consigne: "Lisez le texte et répondez.",
    competence: "CE",
    niveau_vise: "A1",
    format: "qcm",
    contenu: { items: [{ question: "Q?", bonne_reponse: "a" }] },
    validation_status: "validated_auto",
    validation_issues: [],
    search_score: 78,
    fresh: true,
  },
  {
    id: "mock-nr-vert",
    titre: "Compréhension NR — consigne longue",
    consigne: "Lisez le texte et répondez.",
    competence: "CE",
    niveau_vise: "A1",
    format: "qcm",
    contenu: { items: [{ question: "Q?", bonne_reponse: "a" }] },
    validation_status: "needs_review",
    validation_issues: [
      { code: "consigne_too_long", severity: "warning", layer: "L6_pedagogie" },
    ],
    search_score: 75,
    fresh: true,
  },
  {
    id: "mock-excl-stale",
    titre: "Compréhension — récemment utilisé",
    consigne: "Lisez le texte et répondez.",
    competence: "CE",
    niveau_vise: "A1",
    format: "qcm",
    contenu: { items: [{ question: "Q?", bonne_reponse: "a" }] },
    validation_status: "validated_auto",
    validation_issues: [],
    search_score: 90,
    fresh: false,
    recent_occurrences: 3,
  },
  {
    id: "mock-excl-rejected",
    titre: "Compréhension — rejeté",
    consigne: "Lisez le texte et répondez.",
    competence: "CE",
    niveau_vise: "A1",
    format: "qcm",
    contenu: { items: [{ question: "Q?", bonne_reponse: "a" }] },
    validation_status: "rejected",
    validation_issues: [{ code: "invalid_structure", severity: "error" }],
    search_score: 50,
    fresh: true,
  },
];
