// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list_my_groups.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_groups_default = defineTool({
  name: "list_my_groups",
  title: "Lister mes groupes",
  description: "Liste les groupes actifs du formateur connect\xE9 (nom, niveau, nombre de membres).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    const supa = supabaseForUser(ctx);
    const { data, error } = await supa.from("groups").select("id, nom, niveau, is_active, created_at").eq("formateur_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { groups: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_my_sessions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_sessions_default = defineTool2({
  name: "list_my_sessions",
  title: "Lister mes s\xE9ances",
  description: "Liste les s\xE9ances associ\xE9es \xE0 l'utilisateur connect\xE9 (formateur ou \xE9l\xE8ve selon RLS).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Nombre maximum de s\xE9ances \xE0 retourner."),
    statut: z.enum(["planifiee", "en_cours", "terminee", "annulee"]).nullable().describe("Filtrer par statut, ou null pour tous.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, statut }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    const supa = supabaseForUser2(ctx);
    let q = supa.from("sessions").select("id, titre, date, statut, group_id, niveau_cible").order("date", { ascending: false }).limit(limit);
    if (statut) q = q.eq("statut", statut);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { sessions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_my_progression.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_progression_default = defineTool3({
  name: "get_my_progression",
  title: "Ma progression",
  description: "Retourne les derniers r\xE9sultats de l'\xE9l\xE8ve connect\xE9 avec score et comp\xE9tence.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(10).describe("Nombre de r\xE9sultats r\xE9cents \xE0 retourner.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    const supa = supabaseForUser3(ctx);
    const { data, error } = await supa.from("resultats").select("id, score, created_at, exercice_id").order("created_at", { ascending: false }).limit(limit);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { resultats: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gudcenhmzlcvhgbgklzw";
var mcp_default = defineMcp({
  name: "captcf-mcp",
  title: "Cap CF \u2014 TCF IRN",
  version: "0.1.0",
  instructions: "Outils pour consulter les donn\xE9es p\xE9dagogiques de la plateforme Cap CF (TCF IRN). Utilise `list_my_groups` et `list_my_sessions` c\xF4t\xE9 formateur, `get_my_progression` c\xF4t\xE9 \xE9l\xE8ve. L'acc\xE8s est scop\xE9 par RLS \xE0 l'utilisateur connect\xE9.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_groups_default, list_my_sessions_default, get_my_progression_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
